spring:
  data:
    mongodb:
      uri: mongodb+srv://utsavjaiswal2004:bsLWDPqrVJMJraYs@cluster0.7srhtcm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
  application:
    name: JournalApp